import type { Metadata } from 'next';
import Link from 'next/link';
import { business, navigation } from '@/config/business';
import './globals.css';
import { Brand } from '@/components/brand';
import { Analytics } from '@/components/analytics';
import { siteUrl } from '@/lib/seo';
export const metadata: Metadata = {title: {default: 'Infinite Auto Leasing PA | New Cars & Leasing in Philadelphia', template: '%s | Infinite Auto Leasing PA'}, description: 'Find your next new vehicle with Infinite Auto Leasing PA. Personal help with vehicle sourcing, purchases, leasing, and financing in Northeast Philadelphia.'};
export default function RootLayout({children}: {children: React.ReactNode}) {return <html lang="en"><body><Analytics/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness",name:business.name,url:siteUrl,telephone:business.phone.display,email:business.email,address:{"@type":"PostalAddress",streetAddress:business.address.street,addressLocality:business.address.city,addressRegion:business.address.region,postalCode:business.address.postalCode,addressCountry:business.address.country},sameAs:[business.instagram,business.facebook,business.googleBusiness].filter(Boolean),areaServed:business.serviceAreas}).replace(/</g,"\\u003c")}}/><a className="skip" href="#main">Skip to content</a><div className="topbar"><span>{business.address.street} · {business.address.city}, {business.address.region}</span><span>{business.languages.join(' · ')} <a href={business.phone.href}>{business.phone.display} ↗</a></span></div><header className="header"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{navigation.filter(([href])=>href!=='/').map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</nav><Link className="header-cta" href="/find-a-car">Find My Car ↗</Link><details className="mobile-menu"><summary>Menu <span>☰</span></summary><nav aria-label="Mobile navigation">{navigation.map(([href,label])=><a key={href} href={href}>{label}</a>)}<a href={business.phone.href}>Call {business.phone.display}</a></nav></details></header>{children}<footer className="footer"><div className="wrap footer-grid"><div><Brand/><p>Your next car starts with a conversation.</p></div><div><p className="eyebrow">VISIT US</p><p>{business.address.street}<br/>{business.address.city}, {business.address.region} {business.address.postalCode}</p><a href={business.maps} target="_blank" rel="noreferrer">Get directions ↗</a></div><div><p className="eyebrow">LET’S TALK</p><a href={business.phone.href}>{business.phone.display}</a><br/><a href={`mailto:${business.email}`}>Email our team ↗</a><p>{business.languages.join(' · ')}</p></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} {business.name}</span><Link href="/contact">Contact</Link></div></footer><div className="mobile-contact"><a href={business.phone.href}>Call Now ↗</a><a href={business.sms}>Text Us ↗</a><Link href="/find-a-car">Find My Car ↗</Link></div></body></html>}


