import type { Metadata } from 'next';
import Link from 'next/link';
import { business, navigation } from '@/config/business';
import './globals.css';
import { SiteHeader } from '@/components/site-header';
import { Brand } from '@/components/brand';
import { Analytics, PageTransition } from '@/components/analytics';
import { siteUrl } from '@/lib/seo';
export const metadata: Metadata = {title: {default: 'Infinite Auto Leasing PA | New Cars & Leasing in Philadelphia', template: '%s | Infinite Auto Leasing PA'}, description: 'Find your next new vehicle with Infinite Auto Leasing PA. Personal help with vehicle sourcing, purchases, and leasing in Northeast Philadelphia.'};
export default function RootLayout({children}: {children: React.ReactNode}) {return <html lang="en"><body><Analytics/><PageTransition/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness",name:business.name,url:siteUrl,telephone:business.phone.display,email:business.email,address:{"@type":"PostalAddress",streetAddress:business.address.street,addressLocality:business.address.city,addressRegion:business.address.region,postalCode:business.address.postalCode,addressCountry:business.address.country},sameAs:[business.instagram,business.facebook,business.googleBusiness].filter(Boolean),areaServed:business.serviceAreas}).replace(/</g,"\\u003c")}}/><a className="skip" href="#main">Skip to content</a><SiteHeader/>{children}<footer className="footer"><div className="wrap footer-grid"><div><Brand/><p>Your next car starts with a conversation.</p></div><div><p className="eyebrow">VISIT US</p><p>{business.address.street}<br/>{business.address.city}, {business.address.region} {business.address.postalCode}</p><a href={business.maps} target="_blank" rel="noreferrer">Get directions ↗</a></div><div><p className="eyebrow">LET’S TALK</p><a href={business.phone.href}>{business.phone.display}</a><br/><a href={`mailto:${business.email}`}>Email our team ↗</a><p>{business.languages.join(' · ')}</p></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} {business.name}</span><nav aria-label="Footer navigation">{navigation.filter(([href])=>href!=='/').map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</nav></div></footer><div className="mobile-contact"><a href={business.phone.href}>Call Now ↗</a><a href={business.sms}>Text Us ↗</a><Link href="/find-a-car">Find My Car ↗</Link></div></body></html>}


