import Link from 'next/link';
import Image from 'next/image';
import { business } from '@/config/business';
import { Deliveries } from '@/components/sections';
import { Scene } from '@/components/scene';
import { pageMetadata } from '@/lib/seo';
export const metadata=pageMetadata('New Cars & Leasing in Philadelphia','Find your next new car with Infinite Auto Leasing PA. Personal vehicle sourcing, sales and leasing in Philadelphia.','/');
const makes=['LEXUS','BMW','MERCEDES-BENZ','AUDI','TOYOTA','ACURA','VOLVO','NISSAN','HONDA','FORD','CHEVROLET','HYUNDAI'];
export default function Home(){return <main id="main" className="home">
<Scene src="/images/hero.webp" alt="Silver sports sedan outside modern architecture" className="home-hero" priority><p className="eyebrow">INFINITE AUTO LEASING PA</p><h1>Your next car.<br/>A different way there.</h1><p>Vehicle sourcing. Sales. Leasing.<br/>Personally yours, in Philadelphia.</p><div className="actions"><Link className="button" href="/find-a-car">Find My Car <span>↗</span></Link><a className="text-link" href={business.phone.href}>Call {business.phone.display}</a></div><div className="scene-bottom"><span>MORE CHOICE. LESS LEGWORK.</span><span>EXPLORE INFINITE ↓</span></div></Scene>
<section className="editorial"><div className="wrap editorial-grid"><div><p className="eyebrow">THE PERSONAL APPROACH</p><h2>One request.<br/>More possibilities.</h2><p>Your everyday drive. Your family’s next chapter. Tell us what you have in mind—we’ll help you find a car that fits.</p><Link className="text-link" href="/about">Meet Infinite ↗</Link></div><div className="editorial-photo"><Image src="/images/interior.webp" alt="Ivory leather and brushed silver details in a modern vehicle interior" fill sizes="(max-width:700px) 100vw,50vw"/></div></div></section>
<section className="light-intro"><p className="eyebrow">THE FREEDOM TO CHOOSE</p><h2>Not one showroom.<br/>A world of options.</h2><p>Explore available vehicles across many major manufacturers, with one team helping you along the way.</p></section>
<Scene src="/images/coastal-suv.webp" alt="Graphite SUV overlooking the coast, illustrative vehicle image" className="choice-scene"><p className="eyebrow">MADE FOR YOUR NEXT CHAPTER</p><h2>Where will you<br/>go next?</h2><div className="actions"><Link className="button" href="/find-a-car">Explore Your Options <span>↗</span></Link></div></Scene>
<div className="brand-strip"><div className="brand-strip-track">{[0,1].map(copy=><div key={copy} aria-hidden={copy===1?true:undefined}>{makes.map(make=><span key={make}>{make}</span>)}</div>)}</div><p className="small">Manufacturer names identify vehicles you may request. Availability varies.</p></div>
<section className="delivered-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">THE NEXT CHAPTER, STARTED</p><h2>Recently delivered.</h2></div><Link className="text-link" href="/deliveries">Cars We’ve Delivered ↗</Link></div><Deliveries limit={6}/></div></section>
<section className="process-teaser"><div className="wrap"><div><p className="eyebrow">LESS LEGWORK. MORE DRIVING.</p><h2>Simple by design.</h2><Link className="text-link" href="/how-it-works">Discover the process ↗</Link></div><div className="process-rows"><div><b>01</b><span>Tell us what you want.</span></div><div><b>02</b><span>Explore your options.</span></div><div><b>03</b><span>Get your car.</span></div></div></div></section>
<section className="partnership-banner"><div className="wrap"><div><p className="eyebrow">PARTNERSHIPS</p><h2>Good business starts<br/>with a conversation.</h2><p>We’re open to new business relationships and collaboration opportunities.</p></div><Link className="button dark" href="/partnerships">Let’s Work Together <span>↗</span></Link></div></section>
<section className="final-cta"><div className="wrap"><div><p className="eyebrow">PHILADELPHIA BASED. PERSONALLY YOURS.</p><h2>Let’s talk.</h2><a className="contact-number" href={business.phone.href}>{business.phone.display}</a><p>{business.address.street} · Philadelphia, PA 19115</p><div className="actions"><a className="text-link" href={business.phone.href}>Call ↗</a><a className="text-link" href={business.sms}>Text ↗</a><a className="text-link" href={business.maps}>Directions ↗</a></div></div></div></section>
</main>}

