import Link from 'next/link';
import { business } from '@/config/business';
import { getRecentMedia } from '@/lib/instagram/getRecentMedia';
import Image from 'next/image';
export const steps=[['Tell us what you want','Share your make, model, preferred trim, and budget. Still exploring? We can help you narrow it down.'],['Explore purchase or lease options','We compare available vehicles and walk through purchase or lease details that fit your needs.'],['Review the details','You decide what works for you. Availability, pricing, and final terms are confirmed directly with the selling dealer or lessor.'],['Make it yours','Complete the necessary steps with the dealer or lessor, then arrange delivery or pickup with us.']];
export function Steps(){return <div className="steps">{steps.map(([title,copy],i)=><article key={title} data-step={`0${i+1}`}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>}
export function PageHeading({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="page-heading wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><div className="page-description">{children}</div></section>}
export function ContactAside(){return <aside className="contact-aside"><p className="eyebrow">PREFER A CONVERSATION?</p><h3>We’re a phone<br/>call away.</h3><a className="aside-phone" href={business.phone.href}>{business.phone.display} ↗</a><a className="text-link" href={business.sms}>Text us instead ↗</a><hr/><p>{business.address.street}<br/>{business.address.city}, {business.address.region} {business.address.postalCode}</p><p>{business.languages.join(' · ')}</p><p className="small">Vehicle availability, pricing, and lease terms are subject to confirmation. We do not provide financing or act as a credit broker.</p></aside>}
export function FinalCta(){return <section className="final-cta"><div className="wrap"><div><p className="eyebrow">YOUR NEXT MOVE</p><h2>Let’s find your car.</h2><p>Tell us what you’re looking for. We’ll take it from there.</p></div><Link className="button dark" href="/find-a-car">Find My Car <span>↗</span></Link></div></section>}
export async function Deliveries({limit=9}:{limit?:number}){const posts=(await getRecentMedia()).filter(p=>p.status==='sold').slice(0,limit);return posts.length?<div className="delivery-grid">{posts.map(post=><article className="delivery-card" key={post.id}><a href={post.permalink} target="_blank" rel="noreferrer"><div className="delivery-image"><Image src={post.imageUrl} alt={post.vehicleTitle||'Past customer vehicle delivery'} width={720} height={540} unoptimized loading="lazy"/><span>DELIVERED</span></div><div className="delivery-body"><p className="eyebrow">{post.mediaType==='VIDEO'?'REEL · ':''}{new Date(post.timestamp).toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'})}</p><h3>{post.vehicleTitle}</h3><p className="text-link">View post ↗</p></div></a></article>)}</div>:<div className="social-fallback"><div className="social-mark" aria-hidden="true">↗</div><div><h3>Every new drive has a story.</h3><p>For recent customer deliveries, connect with our team{business.instagram?' or visit our Instagram':''}. Vehicles shared here are past deliveries, not current inventory.</p></div>{business.instagram?<a className="button outline" href={business.instagram} target="_blank" rel="noreferrer">Follow Us on Instagram ↗</a>:<Link className="button outline" href="/contact">Connect With Us ↗</Link>}</div>}
